-- Add applicationNo column if missing
ALTER TABLE "public"."Applicant"
ADD COLUMN IF NOT EXISTS "applicationNo" integer;

-- Ensure it is an identity (auto-increment) if not already
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM information_schema.columns c
		WHERE c.table_schema = 'public'
			AND c.table_name = 'Applicant'
			AND c.column_name = 'applicationNo'
			AND c.is_identity = 'YES'
	) THEN
		ALTER TABLE "public"."Applicant"
		ALTER COLUMN "applicationNo" ADD GENERATED BY DEFAULT AS IDENTITY;
	END IF;
END$$;

-- Ensure uniqueness of the generated application number
CREATE UNIQUE INDEX IF NOT EXISTS "Applicant_applicationNo_key"
ON "public"."Applicant"("applicationNo");
